### PR TITLE
change state_cids sequence to bigint

### PR DESCRIPTION
**Pull request by ramilexe**

### CODE REVIEW

**Review by i-norden — COMMENTED** [review]
We should do it for eth.storage_cids_id_seq too

**Comment by srwadleigh** [comment]
I used this command to update the sequences, they both immediately accepted the new max value of a BIGINT, confirmed by way of pg admin.

```
ALTER SEQUENCE eth.state_cids_id_seq AS BIGINT;
ALTER SEQUENCE eth.storage_cids_id_seq AS BIGINT;
```

**Comment by ramilexe** [comment]
> We should do it for eth.storage_cids_id_seq too

done

**Review by i-norden — APPROVED** [review]
LGTM!

**Review by i-norden — APPROVED** [review]
LGTM

**Pull request merged**
